username = input("Введите свое имя ")
title = input("Введите заголовок заметки ")
content = input("Введите описание заметки ")
status = input("Введите статус заметки ")
created_date = input("Введите дату создания заметки в формате dd/mm/yyyy ")
issue_date = input("Введите дату срока исполнения в формате dd/mm/yyyy ")
print (username)
print (title)
print (content)
print (status)
print (created_date)
print (issue_date)
